// Generated by scripts/restia/build-unit-sounds.mjs - do not edit by hand.
/** Monster sprite -> the Heroes 3 creature voice it uses and which sounds exist for it. */
export const UNIT_SOUNDS: Record<string, { voice: string; kinds: ("attack" | "shoot" | "hurt" | "death")[] }> = {
  "arch-devil": { voice: "arch-devil", kinds: ["attack", "hurt", "death"] },
  "argali": { voice: "mountain-ram", kinds: ["attack", "hurt", "death"] },
  "basilisk": { voice: "basilisk", kinds: ["attack", "hurt", "death"] },
  "beholder": { voice: "beholder", kinds: ["attack", "shoot", "hurt", "death"] },
  "black-knight": { voice: "black-knight", kinds: ["attack", "hurt", "death"] },
  "boar": { voice: "boar", kinds: ["attack", "hurt", "death"] },
  "bone-dragon": { voice: "bone-dragon", kinds: ["attack", "hurt", "death"] },
  "centaur": { voice: "centaur", kinds: ["attack", "shoot", "hurt", "death"] },
  "dendroid-guard": { voice: "dendroid-guard", kinds: ["attack", "hurt", "death"] },
  "efreet": { voice: "efreet", kinds: ["attack", "hurt", "death"] },
  "fire-elemental": { voice: "fire-elemental", kinds: ["attack", "hurt", "death"] },
  "goblin": { voice: "goblin", kinds: ["attack", "hurt", "death"] },
  "green-dragon": { voice: "green-dragon", kinds: ["attack", "hurt", "death"] },
  "harpy": { voice: "harpy", kinds: ["attack", "hurt", "death"] },
  "hell-hound": { voice: "hell-hound", kinds: ["attack", "hurt", "death"] },
  "hobgoblin": { voice: "hobgoblin", kinds: ["attack", "hurt", "death"] },
  "horned-demon": { voice: "horned-demon", kinds: ["attack", "hurt", "death"] },
  "imp": { voice: "imp", kinds: ["attack", "hurt", "death"] },
  "kobold": { voice: "kobold", kinds: ["attack", "hurt", "death"] },
  "leprechaun": { voice: "leprechaun", kinds: ["attack", "shoot", "hurt", "death"] },
  "lich": { voice: "lich", kinds: ["attack", "shoot", "hurt", "death"] },
  "lizard-warrior": { voice: "lizard-warrior", kinds: ["attack", "shoot", "hurt", "death"] },
  "lizardman": { voice: "lizardman", kinds: ["attack", "shoot", "hurt", "death"] },
  "magog": { voice: "magog", kinds: ["attack", "shoot", "hurt", "death"] },
  "manticore": { voice: "manticore", kinds: ["attack", "shoot", "hurt", "death"] },
  "medusa": { voice: "medusa", kinds: ["attack", "shoot", "hurt", "death"] },
  "minotaur": { voice: "minotaur", kinds: ["attack", "hurt", "death"] },
  "mountain-ram": { voice: "mountain-ram", kinds: ["attack", "hurt", "death"] },
  "nix": { voice: "nix", kinds: ["attack", "hurt", "death"] },
  "orc-chieftain": { voice: "orc-chieftain", kinds: ["attack", "shoot", "hurt", "death"] },
  "power-lich": { voice: "power-lich", kinds: ["attack", "shoot", "hurt", "death"] },
  "restia-frost-rat": { voice: "goblin", kinds: ["attack", "hurt", "death"] },
  "restia-frost-wolf": { voice: "hell-hound", kinds: ["attack", "hurt", "death"] },
  "rogue": { voice: "rogue", kinds: ["attack", "hurt", "death"] },
  "serpent-fly": { voice: "serpent-fly", kinds: ["attack", "hurt", "death"] },
  "skeleton": { voice: "skeleton", kinds: ["attack", "hurt", "death"] },
  "sprite": { voice: "sprite", kinds: ["attack", "hurt", "death"] },
  "troglodyte": { voice: "troglodyte", kinds: ["attack", "hurt", "death"] },
  "vampire-lord": { voice: "vampire-lord", kinds: ["attack", "shoot", "hurt", "death"] },
  "walking-dead": { voice: "walking-dead", kinds: ["attack", "hurt", "death"] },
  "water-elemental": { voice: "water-elemental", kinds: ["attack", "hurt", "death"] },
  "wight": { voice: "wight", kinds: ["attack", "hurt", "death"] },
  "wolf-rider": { voice: "goblin-wolf-rider", kinds: ["attack", "hurt", "death"] }
};

/** Sound key (public/sounds/<key>.mp3) for a monster action, falling back from shoot to attack. */
export function unitSound(sprite: string, kind: "attack" | "shoot" | "hurt" | "death"): string | undefined {
  const entry = UNIT_SOUNDS[sprite];
  if (!entry) return undefined;
  const pick = entry.kinds.includes(kind) ? kind : kind === "shoot" && entry.kinds.includes("attack") ? "attack" : null;
  return pick ? `units/${entry.voice}-${pick}` : undefined;
}
