/**
 * Order & Chaos roster: the mode's own creatures, split into two sides
 * instead of towns. LAWFUL units are what the player raises on the lawn;
 * CHAOS units are the horde. Every unit has its own ability, and every Lawful
 * unit its own Surge (what a Surge orb dropped on it does). Sprites reuse the
 * game's animated atlases (Heroes III, WoG, the anime towns, DOOM, war machines).
 *
 * Pure data read by ../content.ts (merged into DEFENDERS / ENEMIES / CARDS),
 * so this file only imports types from it and the clock.
 */

import { pace, sec } from "../clock";
import type { BlessingDef, DefDef, DefKind, EnemyDef, FusionRecipe, ProjectileKind, ShotDef } from "../content";

const card = (cost: number, recharge: number) => ({ cost, recharge: sec(recharge), stage: 99 });
const shot = (projectile: ProjectileKind, dmg: number, every: number, extra: Partial<ShotDef> = {}): ShotDef => ({
  projectile, dmg, every: sec(every), windup: 7, range: 9.6, ...extra
});
const lawful = (def: Omit<DefDef, "faction">): DefDef => ({ ...def, faction: "lawful" });

/** The Lawful side, in the order the campaign hands them out. */
export const OC_DEFENDERS: DefDef[] = [
  lawful({ kind: "oc-peasant", name: "Peasant Tithe", sprite: "peasant", hp: 300, card: card(50, 7.5), thorns: 20,
    produce: { value: 25, every: sec(24), first: [sec(5), sec(11)] },
    surge: { kind: "gold", coins: 3, value: 50 },
    blurb: "Pays 25 gold every 24 s, and jabs a pitchfork (20) into every foe that bites it." }),
  lawful({ kind: "oc-longbow", name: "Longbowman", sprite: "archer", hp: 300, card: card(100, 7.5),
    shot: shot("arrow", 20, 1.4, { crit: { every: 4, mult: 3 } }),
    surge: { kind: "storm", shots: 30, gap: 2, dmg: 20, lanes: 1 },
    blurb: "An arrow down its lane every 1.4 s; every 4th arrow is a critical hit (x3)." }),
  lawful({ kind: "oc-dwarf", name: "Dwarf Shieldwall", sprite: "battle-dwarf", hp: 4000, card: card(50, 30), magicResist: 0.5, steadfast: true,
    surge: { kind: "plate", amount: 4000 },
    blurb: "A stubborn wall of 4000; spells and death clouds deal half. Never stunned, cursed, webbed or knocked back." }),
  lawful({ kind: "oc-sapper", name: "Gremlin Sapper", sprite: "gremlin", hp: 300, card: card(25, 30),
    trap: { arm: sec(14), dmg: 1800, radius: 0.95 },
    surge: { kind: "rearm" },
    blurb: "Digs in a charge: armed after 14 s, the first foe on it takes 1800 (so does anything within a tile)." }),
  lawful({ kind: "oc-immolate", name: "Fire Elemental", sprite: "fire-elemental", hp: 1000, card: card(150, 50),
    instant: { kind: "immolate", delay: sec(0.9), dmg: 1800 },
    blurb: "Bursts into flame a moment after it lands: 1800 to every foe in the 3×3." }),
  lawful({ kind: "oc-snow-elf", name: "Snow Elf", sprite: "snow-elf", hp: 300, card: card(175, 7.5),
    shot: shot("frost", 20, 1.5, { chill: true }),
    surge: { kind: "freeze-lane", dur: sec(8), dmg: 200 },
    blurb: "Frost spears: the target moves and bites at half speed for 10 s." }),
  lawful({ kind: "oc-yuuka", name: "Yuuka, Treasurer", sprite: "ba-yuuka", hp: 300, card: card(75, 7.5),
    produce: { value: 15, every: sec(18), first: [sec(6), sec(10)], grow: { step: 5, max: 45 } },
    surge: { kind: "audit", bonus: 100 },
    blurb: "Compound interest: pays 15 gold every 18 s, 5 more each time, up to 45." }),
  lawful({ kind: "oc-sylph", name: "Sylph", sprite: "mgq-sylph", hp: 300, card: card(100, 20),
    gust: { every: sec(10), push: 1.5, range: 6 },
    surge: { kind: "tempest", push: 3 },
    blurb: "Every 10 s a gale blows the foes within 6 tiles in its lane 1.5 tiles back — and flyers off the field." }),
  lawful({ kind: "oc-cyclops", name: "Cyclops Hurler", sprite: "cyclops", hp: 400, card: card(250, 7.5),
    shot: shot("boulder", 45, 2.6, { lob: true, shatter: true, windup: 9, stunEvery: { every: 3, dur: sec(2) } }),
    surge: { kind: "rockfall", count: 3, dmg: 450 },
    blurb: "Lobs boulders (45) over shields and smashes them; every third one stuns for 2 s." }),
  lawful({ kind: "oc-iron-golem", name: "Iron Golem", sprite: "iron-golem", hp: 8000, card: card(125, 30), tall: true, magicResist: 0.5,
    surge: { kind: "stomp", dur: sec(4), dmg: 200 },
    blurb: "An 8000 HP wall too tall to be leapt or bounded over; spells deal half." }),
  lawful({ kind: "oc-storm", name: "Storm Elemental", sprite: "storm-elemental", hp: 1000, card: card(125, 50),
    instant: { kind: "storm", delay: sec(0.8), dmg: 1800 },
    blurb: "Lightning races down its whole lane: 1800 to every foe in it (flyers too)." }),
  lawful({ kind: "oc-sharpshooter", name: "Sharpshooter", sprite: "sharpshooter", hp: 300, card: card(225, 7.5),
    snipe: { dmg: 150, every: sec(5) },
    surge: { kind: "headshot", count: 5, dmg: 1500 },
    blurb: "Every 5 s shoots the toughest foe in its lane for 150, through armour — flyers too." }),
  lawful({ kind: "oc-gnome", name: "Gnome", sprite: "mgq-gnome", hp: 1200, card: card(100, 7.5),
    spikes: { dmg: 20, every: sec(0.5) },
    surge: { kind: "quake", dmg: 400 },
    blurb: "Stone spikes in its tile: foes walk over it (it never blocks) and take 40 a second; it wears down as they do." }),
  lawful({ kind: "oc-pikeman", name: "Pikeman", sprite: "pikeman", hp: 1400, card: card(100, 15),
    melee: { dmg: 30, every: sec(1), reach: 1.05, antiCavalry: true },
    surge: { kind: "phalanx", life: sec(25) },
    blurb: "Stabs every foe within a tile, front or back; double damage to cavalry." }),
  lawful({ kind: "oc-undine", name: "Undine", sprite: "mgq-undine", hp: 400, card: card(150, 15),
    shellGift: { amount: 600, every: sec(12) },
    surge: { kind: "tide", amount: 1500 },
    blurb: "Every 12 s wraps an unshielded neighbour (3×3) in a 600 HP water shell." }),
  lawful({ kind: "oc-halfling", name: "Halfling Grenadier", sprite: "halfling-grenadier", hp: 300, card: card(275, 7.5),
    shot: shot("fireball", 60, 3, { lob: true, splash: 35, windup: 8 }),
    surge: { kind: "cluster", count: 6, dmg: 260 },
    blurb: "Lobs grenades: 60 to the target and 35 to foes within a tile, three lanes." }),
  lawful({ kind: "oc-ice", name: "Ice Elemental", sprite: "ice-elemental", hp: 1000, card: card(75, 40),
    instant: { kind: "frost", delay: sec(0.6), dmg: 200, freeze: sec(10) },
    blurb: "Shatters into a frost nova: every foe in the 3×3 is frozen solid for 10 s (200)." }),
  lawful({ kind: "oc-enchanter", name: "Enchanter", sprite: "enchanter", hp: 300, card: card(125, 7.5),
    produce: { value: 0, every: sec(12), first: [sec(4), sec(8)], mana: 3 },
    surge: { kind: "mana" },
    blurb: "Channels 3 mana to your hero every 12 s." }),
  lawful({ kind: "oc-arch-mage", name: "Arch Mage", sprite: "arch-mage", hp: 300, card: card(300, 7.5),
    shot: shot("bolt", 30, 1.6, { windup: 8, chain: { jumps: 2, falloff: 0.6 } }),
    surge: { kind: "chain", hops: 12, dmg: 300 },
    blurb: "Bolts of 30 that leap on to two more nearby foes (60% each hop)." }),
  lawful({ kind: "oc-genie", name: "Master Genie", sprite: "master-genie", hp: 500, card: card(175, 7.5),
    slowCast: { every: sec(6), count: 3, lanes: 3, dur: sec(8) },
    surge: { kind: "mass-slow", dur: sec(12) },
    blurb: "Every 6 s casts Slow on the three nearest foes across three lanes." }),
  lawful({ kind: "oc-cleric", name: "Zealot Cleric", sprite: "zealot", hp: 300, card: card(175, 7.5),
    shot: shot("holy", 20, 1.5, { windup: 8, holy: true }), heal: { amount: 150, every: sec(5) },
    surge: { kind: "mass-heal", amount: 500 },
    blurb: "Holy orbs (20, double to the undead); every 5 s heals the most wounded defender around it for 150." }),
  lawful({ kind: "oc-faerie", name: "Faerie Dragon", sprite: "faerie-dragon", hp: 800, card: card(250, 10),
    caster: { dmg: 70, every: sec(4) },
    surge: { kind: "meteors", count: 4, dmg: 600 },
    blurb: "Every 4 s a random spell at the nearest foe in its lane: frost (chills), fire (burns around it) or lightning (stuns 1 s)." }),
  lawful({ kind: "oc-aris", name: "Aris, Hyper Cannon", sprite: "ba-aris", hp: 400, card: card(350, 15),
    beam: { charge: sec(8), dmg: 450 },
    surge: { kind: "beam" },
    blurb: "Charges for 8 s while a foe is in her lane, then a beam deals 450 to every foe ahead of her." }),
  lawful({ kind: "oc-ballista", name: "Ballista", sprite: "war-ballista", hp: 1000, card: card(250, 15),
    shot: shot("spear", 70, 3, { pierce: 99, air: true, windup: 10 }),
    surge: { kind: "bolts", count: 3, dmg: 300 },
    blurb: "Heavy bolts (70) that pierce every foe in the lane — flyers too." }),
  lawful({ kind: "oc-leprechaun", name: "Leprechaun", sprite: "leprechaun", hp: 300, card: card(50, 7.5),
    luckyKills: { chance: 0.4, value: 25 },
    surge: { kind: "rainbow", coins: 8, value: 25 },
    blurb: "Luck of the fey: a foe slain in its lane or the two beside it has a 40% chance to drop 25 gold." }),
  lawful({ kind: "oc-crusader", name: "Crusader", sprite: "crusader", hp: 1400, card: card(175, 10),
    melee: { dmg: 50, every: sec(1.2), reach: 1.1, front: true }, zeal: { per: 0.15, max: 5 },
    surge: { kind: "charge", dmg: 500 },
    blurb: "Blade of 50; every foe it slays makes it strike 15% faster (up to five times)." }),
  lawful({ kind: "oc-ammo", name: "Ammo Cart", sprite: "war-ammo-cart", hp: 1000, card: card(100, 20), ammo: 1,
    surge: { kind: "reload" },
    blurb: "Shooters in its 3×3 fire one extra shot with every volley." }),
  lawful({ kind: "oc-hina", name: "Hina, Prefect", sprite: "ba-hina", hp: 400, card: card(325, 7.5),
    shot: shot("bullet", 11, 2, { volley: 5, windup: 6 }),
    surge: { kind: "storm", shots: 60, gap: 1, dmg: 15, lanes: 3 },
    blurb: "Machine-gun bursts: six rounds of 11 every 2 s." }),
  lawful({ kind: "oc-salamander", name: "Salamander", sprite: "mgq-salamander", hp: 1000, card: card(175, 7.5),
    ignite: { splash: 0.5 },
    surge: { kind: "fire-lane", dmg: 1800 },
    blurb: "Shots passing through her catch fire: double damage and half again to the foes beside the target." }),
  lawful({ kind: "oc-phoenix", name: "Phoenix", sprite: "phoenix", hp: 1500, card: card(300, 30), rebirth: true,
    burnAura: { dmg: 40, every: sec(1), reach: 1.5 },
    surge: { kind: "supernova", dmg: 1500 },
    blurb: "Burns every foe within 1.5 tiles in front (40 a second) and rises again once when slain." }),
  lawful({ kind: "oc-first-aid", name: "First Aid Tent", sprite: "war-first-aid-tent", hp: 800, card: card(150, 20),
    laneHeal: { amount: 40, every: sec(2) },
    surge: { kind: "hospital" },
    blurb: "Tends its whole lane: every defender in it heals 40 every 2 s." }),
  lawful({ kind: "oc-akagi", name: "Akagi, Carrier", sprite: "al-akagi", hp: 500, card: card(300, 7.5),
    airstrike: { dmg: 90, every: sec(6), splash: 0.5 },
    surge: { kind: "air-raid", dmg: 600 },
    blurb: "Every 6 s her planes bomb a random foe anywhere on the field (flyers too): 90, half to foes within a tile." }),
  lawful({ kind: "oc-unicorn", name: "War Unicorn", sprite: "war-unicorn", hp: 1300, card: card(225, 15),
    melee: { dmg: 60, every: sec(1.5), reach: 1.1, front: true }, ward: 0.3,
    surge: { kind: "sanctuary", dur: sec(6) },
    blurb: "Horn strike (60); defenders in its 3×3 (itself too) take 30% less damage." }),
  lawful({ kind: "oc-behemoth", name: "Ancient Behemoth", sprite: "ancient-behemoth", hp: 2500, card: card(275, 20), scale: 0.85,
    pounce: { dmg: 900, every: sec(7), range: 1.4 },
    surge: { kind: "rampage", dmg: 1500 },
    blurb: "Every 7 s leaps on the nearest foe within 1.4 tiles ahead and mauls it for 900." }),
  lawful({ kind: "oc-cannon", name: "Cannon", sprite: "war-cannon", hp: 1200, card: card(300, 15),
    shot: shot("rocket", 80, 4.5, { splash: 60, windup: 10 }),
    surge: { kind: "broadside", dmg: 500 },
    blurb: "Shells (80) that burst on the first foe: 60 to foes within a tile, three lanes." }),
  lawful({ kind: "oc-lightning", name: "Lightning Generator", sprite: "war-lightning-generator", hp: 1000, card: card(275, 10),
    chainLightning: { dmg: 90, every: sec(3.5), jumps: 3 },
    surge: { kind: "overload", dmg: 400 },
    blurb: "Every 3.5 s lightning strikes the nearest foe in its lane (flyers too) and leaps to three more nearby." }),
  lawful({ kind: "oc-gorgon", name: "Mighty Gorgon", sprite: "mighty-gorgon", hp: 1800, card: card(300, 30),
    gaze: { front: 1.2, back: 0.3, recover: sec(12), bossDmg: 800 },
    surge: { kind: "stare", bossDmg: 1500 },
    blurb: "Death stare: every 12 s turns the nearest foe within 1.2 tiles to stone (bosses take 800)." }),
  lawful({ kind: "oc-titan", name: "Titan", sprite: "titan", hp: 1500, card: card(450, 15),
    lightning: { dmg: 200, every: sec(3) },
    surge: { kind: "smite", dmg: 300 },
    blurb: "Every 3 s hurls lightning at the nearest foe in its lane (200), however far — flyers too." }),
  lawful({ kind: "oc-archangel", name: "Archangel", sprite: "archangel", hp: 2000, card: card(450, 40),
    melee: { dmg: 80, every: sec(1), reach: 1.1, front: true }, aura: 0.25, resurrect: { every: sec(40) },
    surge: { kind: "resurrect-all" },
    blurb: "Holy blade (80), neighbours act 25% faster, and every 40 s the last defender fallen nearby rises at half health." }),

  // --- Recruited in the Krewlod Badlands and the Void Rift -------------------
  lawful({ kind: "oc-santa", name: "Santa Gremlin", sprite: "wog-santa-gremlin", hp: 300, card: card(75, 7.5),
    shot: shot("gift", 15, 1.5, { range: 4.5, windup: 6 }), produce: { value: 15, every: sec(20), first: [sec(4), sec(8)] },
    surge: { kind: "gold", coins: 5, value: 25 },
    blurb: "Tosses gifts (15, 4.5 tiles) and pays 15 gold every 20 s." }),
  lawful({ kind: "oc-griffin", name: "Royal Griffin", sprite: "royal-griffin", hp: 2400, card: card(125, 20), thorns: 40,
    surge: { kind: "rampage", dmg: 800 },
    blurb: "A 2400 HP guard that tears at every foe biting it: 40 back for every bite." }),
  lawful({ kind: "oc-centaur", name: "Centaur Captain", sprite: "centaur-captain", hp: 500, card: card(150, 7.5),
    shot: shot("spear", 25, 1.6, { pierce: 2 }), kite: { near: 1.2, every: sec(8) },
    surge: { kind: "bolts", count: 4, dmg: 200 },
    blurb: "Throws lances (25) that pierce the first two foes in its lane. When a foe closes within 1.2 tiles it gallops a tile back (if free), at most every 8 s." }),
  lawful({ kind: "oc-mage", name: "Mage", sprite: "mage", hp: 300, card: card(125, 7.5),
    shot: shot("bolt", 25, 1.5, { windup: 8, manaOnHit: 0.25 }),
    surge: { kind: "chain", hops: 8, dmg: 250 },
    blurb: "Magic bolts (25); every hit channels a quarter of a mana point to your hero." }),
  lawful({ kind: "oc-dendroid", name: "Dendroid Soldier", sprite: "dendroid-soldier", hp: 4000, card: card(125, 30), fear: { range: 1.8 },
    surge: { kind: "roots", dur: sec(5), reach: 3 },
    blurb: "A rooted 4000 HP wall; foes within 1.8 tiles in front of it march and strike at half speed." }),
  lawful({ kind: "oc-pegasus", name: "Silver Pegasus", sprite: "silver-pegasus", hp: 1000, card: card(175, 10),
    melee: { dmg: 60, every: sec(1.2), reach: 1.1, front: true, air: true },
    surge: { kind: "skyfall", dmg: 900 },
    blurb: "Strikes the foes in front of it (60) — flyers passing overhead too." }),
  lawful({ kind: "oc-azusa", name: "Azusa, Trapper", sprite: "ba-azusa", hp: 300, card: card(200, 7.5),
    shot: shot("bullet", 15, 1.3, { windup: 5 }), mineLayer: { every: sec(30), reach: 3, max: 2 },
    surge: { kind: "minefield" },
    blurb: "Rifle (15); every 30 s buries a Land Mine (1800) on an empty tile up to 3 ahead — two of hers at most." }),
  lawful({ kind: "oc-belfast", name: "Belfast, Royal Maid", sprite: "al-belfast", hp: 700, card: card(175, 10),
    shot: shot("bullet", 12, 1.6, { windup: 6 }), heal: { amount: 120, every: sec(4) },
    surge: { kind: "mass-heal", amount: 350 },
    blurb: "Deck guns (12); every 4 s serves the most wounded troop around her a 120 HP tea break." }),
  lawful({ kind: "oc-laffey", name: "Laffey, Destroyer", sprite: "al-laffey", hp: 400, card: card(200, 7.5),
    shot: shot("spear", 45, 2.4, { pierce: 3, windup: 6, underShield: true }),
    surge: { kind: "storm", shots: 12, gap: 4, dmg: 45, lanes: 3 },
    blurb: "Torpedoes (45) that run beneath shields and through the first three foes in her lane." }),
  lawful({ kind: "oc-minotaur", name: "Minotaur Guard", sprite: "minotaur", hp: 1800, card: card(175, 15), steadfast: true,
    melee: { dmg: 50, every: sec(1.3), reach: 1.1, front: true, blow: 4 },
    surge: { kind: "whirl", dmg: 600, dur: sec(1) },
    blurb: "A Nighon mercenary sworn to Order: axe (50), every 4th a Mighty Blow (x3). Never stunned, cursed or webbed." }),
  lawful({ kind: "oc-beholder", name: "Beholder", sprite: "beholder", hp: 400, card: card(150, 7.5),
    shot: shot("dark", 22, 1.6, { windup: 7 }), slowCast: { every: sec(9), count: 2, lanes: 1, dur: sec(6) },
    surge: { kind: "chain", hops: 6, dmg: 350 },
    blurb: "A Dungeon eye turned Lawful: rays (22), and every 9 s its gaze slows the two nearest foes in its lane." }),
  lawful({ kind: "oc-naga", name: "Naga Queen", sprite: "naga-queen", hp: 1500, card: card(200, 15),
    melee: { dmg: 80, every: sec(1.5), reach: 1.1, front: true, lanes: 3 },
    surge: { kind: "whirl", dmg: 800, dur: sec(2) },
    blurb: "Six blades strike the foes in front of her in her lane and both beside it (80)." }),
  lawful({ kind: "oc-gold-golem", name: "Gold Golem", sprite: "gold-golem", hp: 5000, card: card(175, 30), tall: true, magicResist: 0.3,
    nuggets: { every: 1000, value: 25 },
    surge: { kind: "gold", coins: 4, value: 50 },
    blurb: "A tall 5000 HP wall (spells deal 30%) that sheds a 25-gold nugget for every 1000 damage it takes." }),
  lawful({ kind: "oc-azure", name: "Azure Dragon", sprite: "azure-dragon", hp: 3200, card: card(500, 40), scale: 0.75, magicResist: 0.5,
    melee: { dmg: 140, every: sec(2), reach: 2.2, front: true }, fear: { range: 2.4 },
    surge: { kind: "blizzard", dur: sec(6), dmg: 400 },
    blurb: "Frost breath (140) on everything 2.2 tiles ahead; its dread slows foes within 2.4 tiles. Spells deal half." }),

  // --- Recruited at the Carnival of Masks -----------------------------------
  lawful({ kind: "oc-rearguard", name: "Grand Elf Rearguard", sprite: "grand-elf", hp: 300, card: card(125, 7.5),
    shot: shot("arrow", 20, 1.4, { back: true }),
    surge: { kind: "storm", shots: 16, gap: 3, dmg: 25, lanes: 3, back: true },
    blurb: "Arrows (20) down its lane — and behind it too, at any foe that has slipped past (diggers, blinkers, devils)." }),
  lawful({ kind: "oc-axe-dwarf", name: "Dwarven Axe-Thrower", sprite: "dwarf", hp: 500, card: card(175, 7.5),
    shot: shot("axe", 20, 2.2, { boomerang: true, pierce: 3, range: 6 }),
    surge: { kind: "whirl", dmg: 500, dur: sec(1) },
    blurb: "Hurls an axe 6 tiles out that cuts up to three foes (20), then spins home and cuts again — the return swing strikes shields from behind." }),
  lawful({ kind: "oc-nymph", name: "Nymph of the Mists", sprite: "nymph", hp: 1000, card: card(50, 15),
    divert: { slow: sec(3) },
    surge: { kind: "scatter", dur: sec(5) },
    blurb: "A foe that bites her is bewildered: after its bite it wanders off into a neighbouring lane, slowed for 3 s." }),
  lawful({ kind: "oc-mechanic", name: "Mechanic's Lodestone", sprite: "mechanic", hp: 300, card: card(125, 7.5),
    magnet: { every: sec(10), range: 4.5 },
    surge: { kind: "magnetize" },
    blurb: "Every 10 s its lodestone tears the helm, armour or shield off the nearest armoured foe within 4.5 tiles, in three lanes." }),
  lawful({ kind: "oc-serpent", name: "Sea Serpent", sprite: "sea-serpent", hp: 1200, card: card(150, 7.5), scale: 0.8,
    devour: { reach: 1.3, cap: 1600, digest: sec(22), bite: 400 },
    surge: { kind: "feast", count: 3, reach: 3 },
    blurb: "Swallows the nearest foe up to 1.3 tiles ahead whole, then spends 22 s digesting. Tougher foes (over 1600) and bosses take a 400 bite instead (4 s to recover)." }),
  lawful({ kind: "oc-cupi", name: "Cupi, Love Archer", sprite: "mgq-cupi", hp: 300, card: card(100, 30),
    charm: { mult: 1 },
    surge: { kind: "charm", count: 2 },
    blurb: "The first foe to bite her falls in love: it turns round and fights the horde for Order, and she is spent. Bosses and smashers are immune." }),

  // --- Hybrids: only made by dropping one seed packet on another unit -------
  lawful({ kind: "oc-frost-archer", name: "Arctic Sharpshooter", sprite: "wog-arctic-sharpshooter", hp: 400, fusion: true,
    shot: shot("frost", 30, 1.3, { chill: true, pierce: 2, crit: { every: 4, mult: 3 } }),
    surge: { kind: "freeze-lane", dur: sec(10), dmg: 300 },
    blurb: "Longbowman + Snow Elf: frost arrows (30) pierce two foes and chill; every 4th is a critical (x3)." }),
  lawful({ kind: "oc-lava-archer", name: "Lava Sharpshooter", sprite: "wog-lava-sharpshooter", hp: 400, fusion: true,
    shot: shot("hellfire", 35, 1.5, { splash: 25 }),
    surge: { kind: "fire-lane", dmg: 1500 },
    blurb: "Longbowman + Fire Elemental: burning bolts (35) that burst on the first foe (25 around it)." }),
  lawful({ kind: "oc-cyclops-king", name: "Cyclops King", sprite: "cyclops-king", hp: 700, fusion: true,
    shot: shot("boulder", 70, 2.6, { lob: true, shatter: true, splash: 40, windup: 9, stunEvery: { every: 2, dur: sec(2) } }),
    surge: { kind: "rockfall", count: 5, dmg: 500 },
    blurb: "Cyclops + Halfling: boulders (70, 40 around) over shields; every second one stuns for 2 s." }),
  lawful({ kind: "oc-diamond-golem", name: "Diamond Golem", sprite: "diamond-golem", hp: 9000, fusion: true, tall: true, magicResist: 0.25, thorns: 60,
    surge: { kind: "plate", amount: 6000 },
    blurb: "Iron Golem + Gnome: a tall 9000 HP crystal wall (spells deal 25%) that cuts every biter for 60." }),
  lawful({ kind: "oc-war-zealot", name: "War Zealot", sprite: "wog-war-zealot", hp: 1200, fusion: true,
    shot: shot("holy", 25, 1.5, { windup: 8, holy: true }), melee: { dmg: 40, every: sec(1), reach: 1.05, antiCavalry: true },
    surge: { kind: "mass-heal", amount: 400 },
    blurb: "Cleric + Pikeman: holy orbs (25, double to the undead) and a halberd for anything that comes close (40, double to cavalry)." }),
  lawful({ kind: "oc-thunderbird", name: "Thunderbird", sprite: "thunderbird", hp: 800, fusion: true,
    chainLightning: { dmg: 110, every: sec(3), jumps: 4 },
    surge: { kind: "smite", dmg: 350 },
    blurb: "Sylph + Storm Elemental: every 3 s lightning strikes the nearest foe in its lane (flyers too) and leaps to four more." }),

  // Summoned only (hero spells): no card.
  lawful({ kind: "oc-earthwall", name: "Earthen Wall", sprite: "stone-golem", hp: 2500, magicResist: 0.5,
    blurb: "A stone wall raised by Earthen Bulwark; crumbles after 30 s." })
];

/** A Chaos creature (fills the defaults the Garrison Wars roster also uses). */
type ChaosInput = Omit<EnemyDef, "might" | "recharge" | "biteEvery" | "faction"> & {
  biteEvery?: number; might?: number; recharge?: number;
};

const chaos = (input: ChaosInput): EnemyDef => ({
  ...input,
  faction: "chaos",
  biteEvery: input.biteEvery ?? 10,
  might: input.might ?? 25 * (input.cost + 1),
  recharge: input.recharge ?? sec(3 + input.cost * 2.5)
});

const WALK = pace(4.7);
const SLOW = pace(6);
const FAST = pace(3);
const RUSH = pace(2.2);

/** The Chaos horde, roughly in the order the campaign introduces them. */
export const OC_ENEMIES: EnemyDef[] = [
  chaos({ kind: "oc-shambler", name: "Shambler", sprite: "walking-dead", hp: 240, speed: WALK, bite: 50, cost: 1, undead: true, lastGasp: 0.3,
    blurb: "The dead of Deyja: slow, relentless and hungry. The first killing blow (unless fire or a blast) leaves it crawling on at 30% health, slower." }),
  chaos({ kind: "oc-imp", name: "Imp Runner", sprite: "imp", hp: 180, speed: RUSH, bite: 30, cost: 1, blink: true,
    blurb: "Fragile, but sprints down the lane and blinks past the first defender it meets (not a tall one)." }),
  chaos({ kind: "oc-trog-helm", name: "Helmed Troglodyte", sprite: "infernal-troglodyte", hp: 300, armor: 450, piece: "helm", speed: WALK, bite: 50, cost: 2, daze: sec(1.5),
    blurb: "A plundered helm takes the first 450 damage; knocked off, it leaves the troglodyte dazed for 1.5 s." }),
  chaos({ kind: "oc-shieldbearer", name: "Skeleton Shieldbearer", sprite: "skeleton-warrior", hp: 300, shield: 1000, speed: WALK, bite: 50, cost: 3, undead: true, stun: { every: 4, dur: sec(1) },
    blurb: "A tower shield soaks 1000 from straight shots in front (lobs, spikes, melee and torpedoes go around it); every 4th strike is a shield bash that stuns for 1 s." }),
  chaos({ kind: "oc-hellhound", name: "Hell Hound", sprite: "hell-hound", hp: 500, speed: WALK, vault: { fastSpeed: RUSH }, bite: 50, cost: 3, poison: { dps: 10, dur: sec(4) },
    blurb: "Races in and leaps over the first defender it meets (not a tall one); its burning bite sears for 10 a second over 4 s." }),
  chaos({ kind: "oc-dragonfly", name: "Dragon Fly Swarm", sprite: "dragon-fly", hp: 250, speed: FAST, bite: 0, cost: 2, flying: true, radius: 0.25, zigzag: { every: 2 },
    blurb: "FLYING: skims over every defender to your gate, flitting into a neighbouring lane every 2 tiles. Only anti-air shots, gusts, lightning and spells reach it." }),
  chaos({ kind: "oc-kobold", name: "Kobold Cutpurse", sprite: "kobold-foreman", hp: 380, speed: FAST, bite: 30, cost: 2, steal: 20, flee: { loot: 60 },
    blurb: "Every strike pockets 20 of your gold; with 60 in its sack it turns and runs for it. Slay it before it escapes to get it all back." }),
  chaos({ kind: "oc-goblin", name: "Goblin Sapper", sprite: "goblin", hp: 500, speed: pace(3.8), bite: 30, cost: 4, keg: { dmg: 1800, fuse: sec(2.5) },
    blurb: "Lights a powder keg at your line: 2.5 s later the 3×3 around it goes up (1800). Frost and stuns hold the fuse. Fire striking an unlit keg sets it off where it stands: the 3×3 blast (1800) tears through its own ranks too." }),
  chaos({ kind: "oc-satyr", name: "Satyr Reveller", sprite: "satyr", hp: 500, speed: WALK, vault: { fastSpeed: FAST }, pogo: true, bite: 50, cost: 4, aura: 0.15,
    blurb: "Bounds over every defender in its way — until a tall one stops it for good. Its pipes quicken allies within 1.5 tiles in its lane by 15%." }),
  chaos({ kind: "oc-death-rider", name: "Death Rider", sprite: "black-knight", hp: 700, armor: 900, piece: "helm", speed: RUSH, bite: 75, cost: 6, cavalry: true, undead: true, joust: 2,
    blurb: "Armoured cavalry at the gallop (900 armour): its first strike is a lance charge (double). Pikes deal double." }),
  chaos({ kind: "oc-berserker", name: "Orc Berserker", sprite: "orc-chieftain", hp: 900, speed: WALK, bite: 60, cost: 4, enrage: { mult: 2, at: "half" },
    blurb: "Below half health it goes berserk: marches and strikes twice as fast." }),
  chaos({ kind: "oc-necromancer", name: "Necromancer", sprite: "gw-necromancer", hp: 800, speed: SLOW, bite: 40, cost: 6, graves: { every: sec(12) },
    blurb: "Raises a grave on an empty tile near it every 12 s. Graves soak shots, block planting and spill the dead at great assaults." }),
  chaos({ kind: "oc-grave", name: "Grave", sprite: "", hp: 700, speed: 0, bite: 0, cost: 0, might: 0, recharge: 0, structure: true, radius: 0.4,
    grave: { raise: "oc-shambler" },
    blurb: "A tombstone: blocks planting on its tile and soaks shots. Every great assault, the dead climb out of it." }),
  chaos({ kind: "oc-harpy", name: "Harpy Snatcher", sprite: "harpy-hag", hp: 500, speed: FAST, bite: 0, cost: 5, snatch: { delay: sec(4) },
    blurb: "Swoops onto your costliest defender and carries it off after 4 s — unless you slay her first." }),
  chaos({ kind: "oc-sandworm", name: "Sandworm", sprite: "olgoi-khorkhoi", hp: 700, speed: WALK, dig: { speed: pace(1.6) }, bite: 55, cost: 5,
    blurb: "Tunnels untouchable under the whole lawn and bursts out behind your lines, facing them." }),
  chaos({ kind: "oc-ogre-shaman", name: "Ogre Shaman", sprite: "ogre-mage", hp: 1200, speed: pace(5.5), bite: 70, biteEvery: 14, cost: 6, aura: 0.35,
    blurb: "Bloodlust drums: allies within 1.5 tiles in its lane march and strike 35% faster." }),
  chaos({ kind: "oc-medusa", name: "Medusa Queen", sprite: "medusa-queen", hp: 600, speed: WALK, bite: 0, cost: 5,
    ranged: { dmg: 25, every: sec(6), range: 3.5, projectile: "arrow", stun: { chance: 1, dur: sec(4) } },
    blurb: "Stops 3.5 tiles out; every 6 s her stone gaze freezes the nearest defender for 4 s." }),
  chaos({ kind: "oc-evil-eye", name: "Evil Eye", sprite: "evil-eye", hp: 500, speed: WALK, bite: 0, cost: 5,
    ranged: { dmg: 40, every: sec(2), range: 5, projectile: "dark", skipWalls: true },
    blurb: "Stares past walls (units with no attack of their own) to burn what stands behind them: 40 every 2 s." }),
  chaos({ kind: "oc-sea-witch", name: "Sea Witch", sprite: "sea-witch", hp: 550, speed: WALK, bite: 0, cost: 5,
    ranged: { dmg: 20, every: sec(3), range: 4.5, projectile: "cloud", lob: true, curse: sec(8) },
    blurb: "Lobs hexes: the defender struck acts at half speed for 8 s." }),
  chaos({ kind: "oc-efreet", name: "Efreet Sultan", sprite: "efreet-sultan", hp: 1100, speed: FAST, bite: 70, cost: 6, fireImmune: true, fireShield: 0.35,
    blurb: "Immune to burning shots; melee that strikes it is scorched for 35% of the blow." }),
  chaos({ kind: "oc-troll", name: "Cave Troll", sprite: "troll", hp: 1300, speed: pace(5.5), regen: 40, bite: 70, biteEvery: 14, cost: 6, shove: { every: 3, dur: sec(1), dmg: 0 },
    blurb: "Regenerates 40 HP a second; every third club blow knocks the defender a tile back (if free) and stuns it for 1 s. Burst it down." }),
  chaos({ kind: "oc-wyvern", name: "Wyvern Monarch", sprite: "wyvern-monarch", hp: 1100, speed: WALK, bite: 0, cost: 6, flying: true, scale: 0.85, skyAttack: { kind: "dive", dmg: 60, every: sec(7), poison: { dps: 15, dur: sec(5) } },
    blurb: "FLYING and armoured in scales (1100 HP): only anti-air shots, gusts, lightning and spells reach it. Every 7 s it dives on the defender beneath it (60, then poison 15 a second for 5 s)." }),
  chaos({ kind: "oc-spider", name: "Spider Princess", sprite: "mgq-spider-princess", hp: 900, speed: WALK, bite: 45, cost: 6, poison: { dps: 15, dur: sec(8) },
    ranged: { dmg: 10, every: sec(7), range: 3, projectile: "cloud", lob: true, splash: true, stun: { chance: 1, dur: sec(3) } },
    blurb: "Casts webs over a 3×3 of your defenders from 3 tiles (bound for 3 s); pressed against a defender she bites and poisons (15 a second)." }),
  chaos({ kind: "oc-carmilla", name: "Carmilla", sprite: "mgq-carmilla", hp: 1000, speed: WALK, bite: 60, cost: 8, drain: 1, rebirth: true, undead: true,
    blurb: "The vampire queen: heals for all she bites and rises once when slain." }),
  chaos({ kind: "oc-pit-lord", name: "Pit Lord", sprite: "pit-lord", hp: 1500, speed: SLOW, bite: 80, cost: 8, revive: { every: sec(10) },
    blurb: "Once on the lawn, raises the last Chaos creature to fall every 10 s." }),
  chaos({ kind: "oc-lucifina", name: "Lucifina", sprite: "mgq-lucifina-chan", hp: 900, speed: WALK, bite: 50, cost: 7, summon: { kind: "oc-imp", every: sec(10) }, summonSpread: true,
    blurb: "Calls Imp Runners into her lane and both beside it every 10 s." }),
  chaos({ kind: "oc-cacodemon", name: "Cacodemon", sprite: "doom-cacodemon", hp: 1600, speed: SLOW, bite: 0, cost: 8, flying: true, skyAttack: { kind: "spit", dmg: 90, every: sec(5) },
    blurb: "FLYING: a floating hell-ball of 1600 HP drifting over your lines, spitting lightning at the defender beneath it every 5 s (90). Anti-air, gusts, lightning and spells only." }),
  chaos({ kind: "oc-dread-knight", name: "Dread Knight", sprite: "dread-knight", hp: 1200, armor: 1100, piece: "helm", speed: RUSH, bite: 75, cost: 9, cavalry: true, deathBlow: 3, undead: true,
    blurb: "Every third strike is a Death Blow (triple). 1100 armour; pikes deal double." }),
  chaos({ kind: "oc-hydra", name: "Chaos Hydra", sprite: "chaos-hydra", hp: 2400, speed: SLOW, bite: 70, cost: 10, cleave: "lanes", regen: 20, scale: 0.8,
    blurb: "Six heads bite its lane and both beside it; regenerates 20 a second." }),
  chaos({ kind: "oc-jotunn", name: "Jotunn Warlord", sprite: "jotunn-warlord", hp: 3400, speed: SLOW, bite: 0, biteEvery: sec(2.5), cost: 13, smash: true, fling: true, flingKind: "oc-imp", scale: 0.85,
    blurb: "Flattens any defender in one blow; wounded, it hurls an Imp deep behind your lines." }),
  chaos({ kind: "oc-cyberdemon", name: "Cyberdemon", sprite: "doom-cyberdemon", hp: 5000, speed: SLOW, bite: 0, cost: 16, magicResist: 0.5, scale: 0.85,
    ranged: { dmg: 180, every: sec(4), range: 5, projectile: "rocket", blast: true },
    blurb: "Rockets (180) from 5 tiles that blast the defenders around the target; spells deal half." }),

  // --- Krewlod Badlands: Chaos coin buys mercenaries from every town ---------
  chaos({ kind: "oc-sellsword", name: "Mercenary Sellsword", sprite: "swordsman", hp: 700, armor: 400, piece: "helm", speed: WALK, bite: 60, cost: 3, purse: 25, flee: { below: 0.3 },
    blurb: "An Erathian blade sold to Chaos: helm and plate take the first 400. Below 30% health it deserts and runs — slay it first and its pay (25 gold) is yours." }),
  chaos({ kind: "oc-seadog", name: "Sea Dog", sprite: "sea-dog", hp: 550, speed: FAST, bite: 45, cost: 3, evade: 3, purse: 15,
    blurb: "A pirate for hire: every third straight shot misses it. Drops its pay (15 gold) when slain." }),
  chaos({ kind: "oc-wolf", name: "Wolf Raider", sprite: "wolf-raider", hp: 520, speed: RUSH, bite: 30, biteEvery: 5, cost: 3, cavalry: true, curse: sec(3),
    blurb: "Races in and bites twice as often; its bites hamstring (the defender acts at half speed for 3 s). Pikes deal double." }),
  chaos({ kind: "oc-nomad", name: "Nomad Outrider", sprite: "nomad", hp: 650, speed: RUSH, bite: 55, cost: 4, cavalry: true, swerve: true,
    blurb: "Gallops in and swerves round the first defender it meets into a free neighbouring lane. Pikes deal double." }),
  chaos({ kind: "oc-rogue", name: "Rogue Cutthroat", sprite: "rogue", hp: 420, speed: FAST, bite: 35, cost: 3, steal: 15, stealth: 5,
    blurb: "Unseen beyond 5 tiles from your gate until it strikes or is hurt; every strike pockets 15 of your gold." }),
  chaos({ kind: "oc-bounty", name: "Bounty Hunter", sprite: "bounty-hunter", hp: 600, speed: WALK, bite: 0, cost: 5,
    ranged: { dmg: 60, every: sec(3), range: 4, projectile: "bullet", hitscan: "bullet" }, costliest: true,
    blurb: "Stops 4 tiles out and guns down the costliest defender in range: 60 every 3 s." }),
  chaos({ kind: "oc-cerberus", name: "Cerberus", sprite: "cerberus", hp: 900, speed: FAST, bite: 45, cost: 5, cleave: "line",
    blurb: "Three heads: every bite also savages the defender standing behind the first." }),

  // --- The Void Rift --------------------------------------------------------
  chaos({ kind: "oc-wraith", name: "Wraith", sprite: "wraith", hp: 500, speed: FAST, bite: 45, cost: 4, regen: 20, manaDrain: 2, undead: true,
    blurb: "Regenerates 20 a second; every strike drains 2 of your hero's mana." }),
  chaos({ kind: "oc-mummy", name: "Mummy", sprite: "mummy", hp: 900, speed: pace(5.5), bite: 50, cost: 4, curse: sec(8), undead: true,
    blurb: "Its touch curses: the defender it strikes acts at half speed for 8 s." }),
  chaos({ kind: "oc-arch-devil", name: "Arch Devil", sprite: "arch-devil", hp: 1400, speed: pace(4.2), bite: 90, cost: 9, teleport: true,
    blurb: "Vanishes at the edge of the lawn and reappears behind your lines, cutting its way back through them." }),
  chaos({ kind: "oc-magog", name: "Magog", sprite: "magog", hp: 650, speed: WALK, bite: 0, cost: 5,
    ranged: { dmg: 45, every: sec(3.5), range: 5, projectile: "fireball", lob: true, splash: true },
    blurb: "Lobs fireballs from 5 tiles over a 3×3 of your troops (45)." }),
  chaos({ kind: "oc-lich", name: "Power Lich", sprite: "power-lich", hp: 800, speed: WALK, bite: 0, cost: 7, undead: true,
    ranged: { dmg: 60, every: sec(4), range: 5, projectile: "cloud", lob: true, splash: true, cloud: true },
    blurb: "Death clouds from 5 tiles over a 3×3 of your troops (60); the undead are spared." }),
  chaos({ kind: "oc-scorpicore", name: "Scorpicore", sprite: "scorpicore", hp: 1100, speed: WALK, bite: 60, cost: 6, stun: { every: 3, dur: sec(3) },
    blurb: "Every third sting paralyzes the defender for 3 s." }),
  chaos({ kind: "oc-lost-soul", name: "Lost Soul", sprite: "doom-lost-soul", hp: 180, speed: pace(2.4), vault: { fastSpeed: pace(1.4) }, bite: 35, cost: 1, undead: true,
    blurb: "A burning skull: darts over the first defender it meets." }),
  chaos({ kind: "oc-pain", name: "Pain Elemental", sprite: "doom-pain-elemental", hp: 900, speed: SLOW, bite: 0, cost: 7, flying: true,
    deathSpawn: { kind: "oc-lost-soul", count: 3 },
    blurb: "FLYING: drifts over your lines and bursts into three Lost Souls when slain." }),
  chaos({ kind: "oc-mancubus", name: "Mancubus", sprite: "doom-mancubus", hp: 2200, speed: SLOW, bite: 0, cost: 9, scale: 0.85,
    ranged: { dmg: 70, every: sec(3.5), range: 3, projectile: "hellfire", hitscan: "flame" },
    blurb: "Flame cannons scorch the nearest defender within 3 tiles (70, magic)." }),
  chaos({ kind: "oc-wakamo", name: "Wakamo, Calamity Fox", sprite: "ba-wakamo", hp: 700, speed: WALK, bite: 0, cost: 7, stealth: 6,
    ranged: { dmg: 150, every: sec(6), range: 5.5, projectile: "bullet", hitscan: "bullet" },
    blurb: "Unseen beyond 6 tiles until she fires or is hurt; snipes the nearest defender within 5.5 tiles for 150." }),
  chaos({ kind: "oc-black-dragon", name: "Black Dragon", sprite: "black-dragon", hp: 3000, speed: WALK, bite: 0, cost: 14, flying: true, anchored: true, magicResist: 0, scale: 0.8, skyAttack: { kind: "breath", dmg: 150, every: sec(6) },
    blurb: "FLYING, immune to spells and too heavy for any gale (not blown away or back): only attacks that reach flyers — anti-air shots and strikes, snipes, bombers, beams and direct lightning — bring down its 3000 HP. Every 6 s it breathes fire on the defender beneath it and the one ahead (150)." }),

  // --- The Carnival of Masks ------------------------------------------------
  chaos({ kind: "oc-phantom", name: "Phantom", sprite: "wog-ghost", hp: 420, speed: WALK, bite: 45, cost: 4, undead: true, phase: { every: sec(8), speed: FAST },
    blurb: "Drifts straight through the defenders in its way — untouchable while it phases (only blasts and hero spells reach it) — then needs 8 s before it can phase again." }),
  chaos({ kind: "oc-werewolf", name: "Werewolf Stalker", sprite: "wog-werewolf", hp: 700, speed: FAST, bite: 55, cost: 4, zigzag: { every: 1.8 },
    blurb: "Every 1.8 tiles it bounds diagonally into a neighbouring lane — never in one lane for long." }),
  chaos({ kind: "oc-revel-queen", name: "Revel Queen", sprite: "commander-succubus", hp: 950, speed: WALK, bite: 50, cost: 7,
    troupe: { kind: "oc-reveller", every: sec(15), dance: sec(1.6) },
    blurb: "Stops on the lawn to dance and calls four Revellers around her (above, below, ahead, behind). They hold while she dances, and she calls the missing ones back every 15 s." }),
  chaos({ kind: "oc-reveller", name: "Reveller", sprite: "familiar", hp: 200, speed: WALK, bite: 30, cost: 0, might: 0, recharge: 0,
    blurb: "A Revel Queen's backup dancer: marches in step with her and holds while she dances. Never marches alone." }),
  chaos({ kind: "oc-arch-vile", name: "Arch-vile", sprite: "doom-arch-vile", hp: 750, speed: WALK, bite: 45, cost: 7,
    raiseDead: { range: 2.5, channel: sec(2.5), every: sec(6), fresh: sec(10) },
    blurb: "Stops over an ally slain within 2.5 tiles and 2.5 s later raises it where it fell, whole. Stun it, freeze it, blow it back or slay it to break the spell." }),
  chaos({ kind: "oc-juggernaut", name: "Juggernaut", sprite: "juggernaut", hp: 1500, speed: pace(3.6), bite: 90, cost: 8, roller: { dmg: 800 },
    blurb: "Rolls over every defender in its lane (800 to each). A tall defender stops it cold; spikes pop it and mines blow it apart." }),
  chaos({ kind: "oc-ram", name: "Battering Ram", sprite: "mountain-ram", hp: 800, speed: FAST, bite: 50, cost: 5, shove: { every: 0, dur: sec(2), dmg: 150 },
    blurb: "Its first charge butts the defender it meets a tile back (if the tile is free) and stuns it for 2 s (150)." })
];

type OcBlessingId = "surge-chalice" | "crown-of-dragontooth" | "helm-of-enlightenment" | "ambassadors-sash" | "charm-of-mana" | "endless-purse" | "spirit-of-oppression";

/** Order & Chaos artifacts on top of Garrison Wars' blessings (never offered there). */
export const OC_BLESSINGS: Record<OcBlessingId, BlessingDef> = {
  "surge-chalice": {
    id: "surge-chalice", name: "Pendant of Courage", icon: "/assets/artifacts_major-pendant_of_courage.webp",
    blurb: "Start each battle with a Surge orb and carry up to four."
  },
  "crown-of-dragontooth": {
    id: "crown-of-dragontooth", name: "Crown of Dragontooth", icon: "/assets/artifacts_relic-crown_of_dragontooth.webp",
    blurb: "Valor for Ascensions builds 50% faster."
  },
  "helm-of-enlightenment": {
    id: "helm-of-enlightenment", name: "Helm of Heavenly Enlightenment", icon: "/assets/artifacts_relic-helm_of_heavenly_enlightenment.webp",
    blurb: "Ascensions last 50% longer."
  },
  "ambassadors-sash": {
    id: "ambassadors-sash", name: "Ambassador's Sash", icon: "/assets/artifacts_major-ambassadors_sash.webp",
    blurb: "Seed packets cost 15% less gold."
  },
  "charm-of-mana": {
    id: "charm-of-mana", name: "Charm of Mana", icon: "/assets/artifacts_minor-charm_of_mana.webp",
    blurb: "Spells recover 40% faster."
  },
  "endless-purse": {
    id: "endless-purse", name: "Endless Purse of Gold", icon: "/assets/artifacts_major-endless_purse_of_gold.webp",
    blurb: "Gold falls from the sky 40% more often."
  },
  "spirit-of-oppression": {
    id: "spirit-of-oppression", name: "Spirit of Oppression", icon: "/assets/artifacts_minor-spirit_of_oppression.webp",
    blurb: "The horde's war drums fall silent: Chaos auras (Ogre Shamans' bloodlust) have no effect."
  }
};

/** Hybrids (PvZ-Hybrid style): drop the second seed packet on the first unit (either order). */
export const OC_FUSIONS: readonly FusionRecipe[] = [
  { a: ["oc-longbow"], b: ["oc-snow-elf"], result: "oc-frost-archer" },
  { a: ["oc-longbow"], b: ["oc-immolate"], result: "oc-lava-archer" },
  { a: ["oc-cyclops"], b: ["oc-halfling"], result: "oc-cyclops-king" },
  { a: ["oc-iron-golem"], b: ["oc-gnome"], result: "oc-diamond-golem" },
  { a: ["oc-cleric"], b: ["oc-pikeman"], result: "oc-war-zealot" },
  { a: ["oc-sylph"], b: ["oc-storm"], result: "oc-thunderbird" }
];

/** A Lawful unit's Ascended form: its ultimate, while a Valor crown burns. */
export type OcUltimate = {
  name: string;
  /** The form's sprite (the unit's own when unset). */
  sprite?: string;
  blurb: string;
  /** Changes to the level-1 unit before the form is scaled. */
  patch: (base: DefDef) => Partial<DefDef>;
};

const shotWith = (base: DefDef, extra: Partial<ShotDef>): Partial<DefDef> => (base.shot ? { shot: { ...base.shot, ...extra } } : {});

export const OC_ULTIMATES: Readonly<Record<DefKind, OcUltimate>> = {
  "oc-peasant": { name: "Golden Harvest", blurb: "The harvest is in: pays gold every 5 s.",
    patch: (b) => ({ produce: b.produce && { ...b.produce, every: sec(5) } }) },
  "oc-longbow": { name: "Marksman Captain", sprite: "marksman", blurb: "Two arrows at a time down its lane and both beside it; every 3rd is a critical.",
    patch: (b) => shotWith(b, { volley: 1, lanes: 3, crit: { every: 3, mult: 3 } }) },
  "oc-dwarf": { name: "Runic Bulwark", blurb: "Runes flare: spells deal a quarter, and every biter is cut back hard.",
    patch: () => ({ magicResist: 0.25, thorns: 80 }) },
  "oc-snow-elf": { name: "Glacial Spear", blurb: "Spears pierce three foes; every third one freezes its target solid.",
    patch: (b) => shotWith(b, { pierce: 3, freezeEvery: 3 }) },
  "oc-yuuka": { name: "Audit Season", blurb: "Pays at the full compound rate every 6 s.",
    patch: (b) => ({ produce: b.produce && { ...b.produce, every: sec(6), value: b.produce.grow?.max ?? b.produce.value } }) },
  "oc-sylph": { name: "Hurricane", blurb: "A gale every 3 s that reaches across the whole lawn.",
    patch: (b) => ({ gust: b.gust && { ...b.gust, every: sec(3), range: 9 } }) },
  "oc-cyclops": { name: "Cyclops King", sprite: "cyclops-king", blurb: "Boulders every 2 s that burst around the target; every other one stuns.",
    patch: (b) => shotWith(b, { every: sec(2), splash: 40, stunEvery: { every: 2, dur: sec(2) } }) },
  "oc-iron-golem": { name: "Steel Colossus", sprite: "steel-golem", blurb: "Spells deal a quarter, and every biter is cut back.",
    patch: () => ({ magicResist: 0.25, thorns: 60 }) },
  "oc-sharpshooter": { name: "Deadeye", blurb: "Shoots the toughest foe in its lane every 2.5 s, harder.",
    patch: (b) => ({ snipe: b.snipe && { dmg: 200, every: sec(2.5) } }) },
  "oc-gnome": { name: "Earthshaker", blurb: "The spikes grow far deadlier.",
    patch: (b) => ({ spikes: b.spikes && { ...b.spikes, dmg: b.spikes.dmg * 3 } }) },
  "oc-pikeman": { name: "Halberd Line", sprite: "halberdier", blurb: "A heavier halberd that reaches 1.6 tiles, into both neighbouring lanes.",
    patch: (b) => ({ melee: b.melee && { ...b.melee, dmg: 45, reach: 1.6, lanes: 3 } }) },
  "oc-undine": { name: "Tidal Veil", blurb: "A far thicker water shell for a neighbour every 4 s.",
    patch: (b) => ({ shellGift: b.shellGift && { amount: 900, every: sec(4) } }) },
  "oc-halfling": { name: "Grenade Barrage", blurb: "Three grenades per throw.",
    patch: (b) => shotWith(b, { volley: 2 }) },
  "oc-enchanter": { name: "Ley Line", blurb: "Channels 5 mana every 6 s.",
    patch: (b) => ({ produce: b.produce && { ...b.produce, every: sec(6), mana: 5 } }) },
  "oc-arch-mage": { name: "Storm of Bolts", blurb: "Bolts leap on to five more foes, losing little.",
    patch: (b) => shotWith(b, { chain: { jumps: 5, falloff: 0.8 } }) },
  "oc-genie": { name: "Wishmaster", blurb: "Every 3 s slows the five nearest foes across three lanes.",
    patch: (b) => ({ slowCast: b.slowCast && { ...b.slowCast, every: sec(3), count: 5 } }) },
  "oc-cleric": { name: "Holy Choir", sprite: "zealot", blurb: "Bigger heals, every 2 s.",
    patch: (b) => ({ heal: b.heal && { amount: 200, every: sec(2) } }) },
  "oc-faerie": { name: "Rainbow Barrage", blurb: "A random spell every 1.5 s.",
    patch: (b) => ({ caster: b.caster && { ...b.caster, every: sec(1.5) } }) },
  "oc-aris": { name: "Hikari yo!", blurb: "The cannon charges in 3 s.",
    patch: (b) => ({ beam: b.beam && { ...b.beam, charge: sec(3) } }) },
  "oc-ballista": { name: "Siege Engine", blurb: "Piercing bolts every 1.2 s.",
    patch: (b) => shotWith(b, { every: sec(1.2) }) },
  "oc-leprechaun": { name: "Pot of Gold", blurb: "Every foe slain in its three lanes drops gold.",
    patch: (b) => ({ luckyKills: b.luckyKills && { ...b.luckyKills, chance: 1 } }) },
  "oc-crusader": { name: "Champion", sprite: "champion", blurb: "Strikes every 0.6 s, 1.6 tiles ahead.",
    patch: (b) => ({ melee: b.melee && { ...b.melee, every: sec(0.6), reach: 1.6 } }) },
  "oc-ammo": { name: "Munitions Train", blurb: "Shooters around it fire three extra shots per volley.",
    patch: () => ({ ammo: 3 }) },
  "oc-hina": { name: "Prefect's Fury", blurb: "Twelve rounds every 1.5 s.",
    patch: (b) => shotWith(b, { volley: 11, every: sec(1.5) }) },
  "oc-salamander": { name: "Living Flame", blurb: "Also burns every foe within 1.2 tiles in front, every second.",
    patch: () => ({ burnAura: { dmg: 40, every: sec(1), reach: 1.2 } }) },
  "oc-phoenix": { name: "Solar Flare", blurb: "Burns twice as hot, and every foe within 3 tiles in front.",
    patch: (b) => ({ burnAura: b.burnAura && { ...b.burnAura, dmg: 80, reach: 3 } }) },
  "oc-first-aid": { name: "Field Hospital", blurb: "Its whole lane heals every second, three times as much.",
    patch: (b) => ({ laneHeal: b.laneHeal && { amount: 120, every: sec(1) } }) },
  "oc-akagi": { name: "Carrier Strike Group", blurb: "Planes bomb a foe every 2.5 s.",
    patch: (b) => ({ airstrike: b.airstrike && { ...b.airstrike, every: sec(2.5) } }) },
  "oc-unicorn": { name: "Sacred Aegis", blurb: "Troops in its 3×3 take 60% less damage; its horn blinds (35%).",
    patch: (b) => ({ ward: 0.6, melee: b.melee && { ...b.melee, stun: { chance: 0.35, dur: sec(3) } } }) },
  "oc-behemoth": { name: "Primal Hunger", blurb: "Leaps 2.5 tiles every 3 s, mauling harder.",
    patch: (b) => ({ pounce: b.pounce && { dmg: 1200, every: sec(3), range: 2.5 } }) },
  "oc-cannon": { name: "Grand Battery", blurb: "Shells every 2.2 s with a much bigger burst around the target.",
    patch: (b) => shotWith(b, { every: sec(2.2), splash: 100 }) },
  "oc-lightning": { name: "Tesla Storm", blurb: "Lightning every 1.5 s, leaping to five more foes.",
    patch: (b) => ({ chainLightning: b.chainLightning && { ...b.chainLightning, every: sec(1.5), jumps: 5 } }) },
  "oc-gorgon": { name: "Stone Tempest", blurb: "Its stare reaches 2.5 tiles and recovers in 4 s.",
    patch: (b) => ({ gaze: b.gaze && { ...b.gaze, front: 2.5, recover: sec(4) } }) },
  "oc-titan": { name: "Wrath of the Heavens", blurb: "Lightning every 1.2 s.",
    patch: (b) => ({ lightning: b.lightning && { ...b.lightning, every: sec(1.2) } }) },
  "oc-archangel": { name: "Seraph", blurb: "A mightier blade; neighbours act 50% faster; raises the fallen every 12 s.",
    patch: (b) => ({ melee: b.melee && { ...b.melee, dmg: 120 }, aura: 0.5, resurrect: { every: sec(12) } }) },
  "oc-santa": { name: "Gift Rush", blurb: "Bigger gifts of gold, every 8 s.",
    patch: (b) => ({ produce: b.produce && { ...b.produce, value: 25, every: sec(8) } }) },
  "oc-griffin": { name: "Royal Talon", blurb: "Talons for the foes in front every second, and far harsher retaliation.",
    patch: () => ({ thorns: 100, melee: { dmg: 60, every: sec(1), reach: 1.1, front: true } }) },
  "oc-centaur": { name: "Stormlance", blurb: "Two lances at a time, through every foe in the lane — flyers too.",
    patch: (b) => shotWith(b, { pierce: 99, volley: 1, air: true }) },
  "oc-mage": { name: "Archmage's Focus", sprite: "arch-mage", blurb: "Every bolt channels a whole mana point.",
    patch: (b) => shotWith(b, { manaOnHit: 1 }) },
  "oc-dendroid": { name: "Elder Treant", blurb: "Roots reach 3.5 tiles and lash every biter.",
    patch: () => ({ fear: { range: 3.5 }, thorns: 40 }) },
  "oc-pegasus": { name: "Starwing", blurb: "Heavier strikes in three lanes at once, flyers too.",
    patch: (b) => ({ melee: b.melee && { ...b.melee, dmg: 90, lanes: 3 } }) },
  "oc-azusa": { name: "Trap Master", blurb: "Buries a mine every 8 s, four at most.",
    patch: (b) => ({ mineLayer: b.mineLayer && { ...b.mineLayer, every: sec(8), max: 4 } }) },
  "oc-belfast": { name: "Tea Time", blurb: "Bigger heals, every 1.5 s.",
    patch: (b) => ({ heal: b.heal && { amount: 200, every: sec(1.5) } }) },
  "oc-laffey": { name: "Rabbit Rush", blurb: "Torpedoes every 0.9 s.",
    patch: (b) => shotWith(b, { every: sec(0.9) }) },
  "oc-minotaur": { name: "Minotaur King", sprite: "minotaur-king", blurb: "A heavier axe; every other blow is a Mighty Blow.",
    patch: (b) => ({ melee: b.melee && { ...b.melee, dmg: 75, blow: 2 } }) },
  "oc-beholder": { name: "Eye Tyrant", blurb: "Three rays per volley; slows the four nearest foes across three lanes.",
    patch: (b) => ({ ...shotWith(b, { volley: 2 }), slowCast: b.slowCast && { ...b.slowCast, count: 4, lanes: 3 } }) },
  "oc-naga": { name: "Tidal Blades", blurb: "Heavier blades that reach 2.2 tiles in three lanes.",
    patch: (b) => ({ melee: b.melee && { ...b.melee, dmg: 110, reach: 2.2 } }) },
  "oc-gold-golem": { name: "Midas Heart", blurb: "Sheds a nugget for every 400 damage it takes.",
    patch: (b) => ({ nuggets: b.nuggets && { ...b.nuggets, every: 400 } }) },
  "oc-azure": { name: "Frost Tyrant", blurb: "Breathes on three lanes; its dread reaches 4 tiles.",
    patch: (b) => ({ melee: b.melee && { ...b.melee, lanes: 3 }, fear: { range: 4 } }) },
  "oc-rearguard": { name: "Twin Quivers", blurb: "Two arrows at a time, both ways; every third is a critical (x3).",
    patch: (b) => shotWith(b, { volley: 1, crit: { every: 3, mult: 3 } }) },
  "oc-axe-dwarf": { name: "Whirling Axes", sprite: "battle-dwarf", blurb: "Two axes at a time that fly the whole lane and cut through six foes each way.",
    patch: (b) => shotWith(b, { volley: 1, pierce: 6, range: 9.6 }) },
  "oc-nymph": { name: "Mist Queen", sprite: "oceanid", blurb: "Foes she bewilders wander off slowed for 10 s.",
    patch: () => ({ divert: { slow: sec(10) } }) },
  "oc-mechanic": { name: "Grand Lodestone", blurb: "Tears off a helm, armour or shield every 3 s, anywhere in three lanes.",
    patch: (b) => ({ magnet: b.magnet && { every: sec(3), range: 9 } }) },
  "oc-serpent": { name: "Leviathan", sprite: "haspid", blurb: "Swallows foes up to 4000 toughness from 2 tiles away and digests in 5 s; bites for 800.",
    patch: (b) => ({ devour: b.devour && { reach: 2, cap: 4000, digest: sec(5), bite: 800 } }) },
  "oc-cupi": { name: "Heartbreaker", blurb: "The foe she charms is healed in full and strikes twice as hard for Order.",
    patch: () => ({ charm: { mult: 2 } }) }
};
